---
title: "PATNET Seminar Project"
author: "Jhalak Gope"
date: '2022-06-21'
output:
  html_document:
    theme: yeti
    toc_depth: 3
    toc: true
    toc_float: true
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
```
## General Data Preparation
### Loading Libraries
```{r, warning=FALSE, results="hide"}
library(dplyr)
library(sna)
library(network)
library(networkD3)
```

### Loading Dataset
```{r}
load("res_sem.RData")
```
### Data cleaning
```{r}
IPC4 <- substr(joined_IPC_Inv$IPC, start = 1, stop = 4) #extracting the IPC3 from the original sorted dataset
IPC4 <- as.data.frame(IPC4) #defining the character vector as a dataframe
data_final <- cbind(joined_IPC_Inv, IPC4) #combining the newly created IPC3 containing dataframe with the main dataframe
rm(joined_IPC_Inv) & rm(IPC4) #removing the dataset to free memory
data_final <- subset(data_final, select = -c(IPC,ctry_code)) # dropping columns
colnames(data_final)[colnames(data_final)=="IPC"] <- "IPC4" #changing the column name to IPC3head
data_final <- (data_final %>% 
                 filter(IPC4=="F03D")) #creating subset of Wind Energy Industry (F03D)
data_final_F03D <- (data_final %>% 
                 filter(app_year>= 1996 & app_year <= 2016)) #limiting years from 1996 to 2016
data_1 <- (data_final_F03D %>%
           mutate(city = replace(city, city == "", NA)))#making the empty values NA
data_2 <- na.omit(data_1) #getting rid of NA values
data_main <- data_2[!duplicated(data_2),]#getting rid of duplicate rows
# ranking cities according to patents
data_main_city_rank <- (data_main %>%
                          group_by(city) %>% 
                          count(city, sort = TRUE,  name = "patents"))
# keeping first 15 patent owning cities
data_main_15 <- head(data_main_city_rank,15)
```
## General Insights from the Data
### Top 15 most patent owning cities
```{r, results="asis"}
data_main_15 %>%
  knitr::kable(caption = "Top 15 German Cities in Wind Motor Innovation") %>% 
  kableExtra::kable_styling(bootstrap_options = c("hover", "bordered"), full_width = FALSE)
```
### Regional Innovation Map
```{r}

```


## Network Data Preparation
### Inventor's network
```{r}
inv_aff <- (data_main %>% 
              select("appln_id","person_id"))
inv_aff_2mode <- table(inv_aff)
dim(inv_aff_2mode)
inv_aff_adj <- inv_aff_2mode %*% t(inv_aff_2mode)
dim(inv_aff_adj)
class(inv_aff_adj)
inv_aff_nw <-  network(inv_aff_adj,
                       matrix.type="adjacency",
                       directed=T)  # convert into 'network' format
print.network(inv_aff_nw) # Basic information about the network
```
### City's network (for top 15 cities)
```{r}
inv_city <- (data_main %>% 
               select("city","appln_id"))
inv_city_2mode <-  table(inv_city)   # cross tabulate -> 2-mode sociomatrix
dim(inv_city_2mode)
inv_city_adj <- inv_city_2mode %*% t(inv_city_2mode)
dim(inv_city_adj)
class(inv_city_adj)
inv_city_nw <-  network(inv_city_adj,
                        matrix.type="adjacency",
                        directed=T)  # convert into 'network' format
print.network(inv_city_nw) # basic information about the network





```

## Plotting Networks
### Inventor's network
```{r}
par(mar=c(0,0,1,0))
plot.network(inv_aff_nw,
             displayisolates = T) + 
  title("Network of the inventors of all cities")

par(mar=c(0,0,0,0))
simpleNetwork(inv_aff,
              nodeColour = "blue",
              linkColour = "black",
              fontSize = 12,
              opacity = 100,
              zoom = TRUE)
```
### City's network
```{r}
par(mar=c(0,0,1,0))
plot.network(inv_city_nw, 
             displayisolates = T,
             label = network.vertex.names(inv_city_nw)) +
  title("Network of the cities")

par(mar=c(0,0,0,0))
simpleNetwork(inv_city,
              nodeColour = "lightbuue",
              linkColour = "gray",
              fontSize = 12,
              opacity = 50,
              zoom = TRUE)
```
